version: '3.4'

services:
  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    ports:
      - "5000:443"
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    ports:
      - "5001:443"
    build:
      context: .
      dockerfile: OrderApi/Dockerfile


  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    ports:
      - "5002:443"
    build:
      context: .
      dockerfile: ProductApi/Dockerfile

